---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: present

- name: Add Kubernetes apt-key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present

- name: Install Helm
  ansible.builtin.get_url:
    url: https://get.helm.sh/helm-v3.7.0-linux-amd64.tar.gz
    dest: /tmp
    mode: '0755'


- name: Unarchive Helm
  ansible.builtin.unarchive:
    src: /tmp/helm-v3.7.0-linux-amd64.tar.gz
    dest: /tmp
    remote_src: true

- name: Copy Helm binary
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0755'
    remote_src: true

- name: Install Kind
  ansible.builtin.shell: |
    [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
    [ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-arm64
    chmod +x ./kind
    sudo mv ./kind /usr/local/bin/kind
  args:
    executable: /bin/bash
  changed_when: false
