---
- name: Install Kubeslice-cli
  ansible.builtin.get_url:
    url: https://github.com/kubeslice/kubeslice-cli/releases/download/0.4.4/kubeslice-cli-0.4.4-linux-amd64
    dest: /usr/local/bin/kubeslice-cli
    mode: 'a+x'
    validate_certs: false
