---
#
# Tasks to be applied to all servers
#

- name: Check connectivity
  ansible.builtin.ping:
    data: alive
  tags: check

# Add further tasks for the common role (applied to all servers) to this playbook...

...
